sudo: required
dist: bionic
language: java
jdk:
  - oraclejdk11
env:
  global:
    - PROJECTS=$( find hibernate-search -name pom.xml -print -or -path '*/target/*' -prune | sort | xargs -n 1 dirname )
cache:
  directories:
    - $HOME/.m2
install:
  # The Maven install provided by Travis is outdated, use Maven wrapper to get the latest version
  - mvn -N io.takari:maven:wrapper
  - ./mvnw -v
  # first run to download all the Maven dependencies without logging
  - MVNW=$( readlink -f ./mvnw ) ;
    for project in $PROJECTS ;
    do
        pushd "$project" ;
        $MVNW -B -q clean dependency:resolve || exit $? ;
        popd ;
    done
script:
  # Tests are skipped, because for most demos they require a specific environment
  - MVNW=$( readlink -f ./mvnw ) ;
    for project in $PROJECTS ;
    do
        pushd "$project" ;
        $MVNW clean package -DskipTests || exit $? ;
        popd ;
    done
